---
abstract: 'Perl Class for getting DICOM DCMTK dcmdump output for DICOM file.'
author:
  - 'Michal Spacek <skim@cpan.org>'
build_requires:
  English: 0
  Error::Pure::Utils: 0.22
  ExtUtils::MakeMaker: 6.36
  Test::More: 0
  Test::NoWarnings: 0
configure_requires:
  ExtUtils::MakeMaker: 6.36
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.16'
license: bsd
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Dicom-DCMTK-DCMDump-Get
no_index:
  directory:
    - examples
    - inc
    - t
    - xt
requires:
  Class::Utils: 0.05
  perl: 5.8.0
resources:
  bugtracker: https://rt.cpan.org/Public/Dist/Display.html?Name=Dicom-DCMTK-DCMDump-Get
  homepage: https://github.com/tupinek/Dicom-DCMTK-DCMDump-Get
  license: http://opensource.org/licenses/bsd-license.php
  repository: git://github.com/tupinek/Dicom-DCMTK-DCMDump-Get
version: '0.03'
